string1 = "One day "
string2 = "This morning "
string3 = "Yesterday "
string4 = "my shoelace "
string5 = "my pet gopher "
string6 = "my teacher "
string7 = "my mom "
string8 = "my eyeball "
string9 = "wasn't feeling well "
string10 = "slipped on a banana peel "
string11 = "had a little too much sugar "
string12 = "won a trophy because "
string13 = "drove a racecar "
string14 = "in "
string15 = "under "
string16 = "on top of "
string17 = "next to "
string18 = "a hedgehog "
string19 = "an orange beetle "
string20 = "a snail "
string21 = "a kangaroo "
string22 = "a radish "
string23 = "got braces "
string24 = "a golden tooth "
string25 = "went to the circus "
string26 = "attacked "
string27 = "looked "
string28 = "rescued "
string29 = "created "
string30 = "trapped "
string31 = "invented "
string32 = "promised "
string33 = "their "
string34 = "his "
string35 = "her "
string36 = "a "
string37 = "and "
string38 = "then "
string39 = "meanwhile "
string40 = "unfortunately "
string41 = "because "
string42 = "got "
string43 = "who "
string44 = "he "
string45 = "she "

story = (string1 + ", " + string4 + string11 + ". " + string39 + string18 +  string37 + string19 + string40 + string26 + string5 + ".")
print(story.upper())

story2 = (string2 + ", " + string7 + string12 + string45 + string28 + string22 + string28 + string8 + string9 + string37 + string23 + ".")
print(story2.lower())
print(story2.replace(string28, string30))